/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as SidebarStyleRouteImport } from './routes/_sidebar/style'
import { Route as SidebarShortcutsRouteImport } from './routes/_sidebar/shortcuts'
import { Route as SidebarNotesRouteImport } from './routes/_sidebar/notes'
import { Route as SidebarKeytermsRouteImport } from './routes/_sidebar/keyterms'
import { Route as SidebarHomeRouteImport } from './routes/_sidebar/home'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'

const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarStyleRoute = SidebarStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarShortcutsRoute = SidebarShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarNotesRoute = SidebarNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarKeytermsRoute = SidebarKeytermsRouteImport.update({
  id: '/keyterms',
  path: '/keyterms',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarHomeRoute = SidebarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SidebarRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof AuthOnboardingRoute
  '/home': typeof SidebarHomeRoute
  '/keyterms': typeof SidebarKeytermsRoute
  '/notes': typeof SidebarNotesRoute
  '/shortcuts': typeof SidebarShortcutsRoute
  '/style': typeof SidebarStyleRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof AuthOnboardingRoute
  '/home': typeof SidebarHomeRoute
  '/keyterms': typeof SidebarKeytermsRoute
  '/notes': typeof SidebarNotesRoute
  '/shortcuts': typeof SidebarShortcutsRoute
  '/style': typeof SidebarStyleRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_sidebar': typeof SidebarRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_sidebar/home': typeof SidebarHomeRoute
  '/_sidebar/keyterms': typeof SidebarKeytermsRoute
  '/_sidebar/notes': typeof SidebarNotesRoute
  '/_sidebar/shortcuts': typeof SidebarShortcutsRoute
  '/_sidebar/style': typeof SidebarStyleRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/home'
    | '/keyterms'
    | '/notes'
    | '/shortcuts'
    | '/style'
    | '/notes/$noteId'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/home'
    | '/keyterms'
    | '/notes'
    | '/shortcuts'
    | '/style'
    | '/notes/$noteId'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_sidebar'
    | '/_auth/onboarding'
    | '/_sidebar/home'
    | '/_sidebar/keyterms'
    | '/_sidebar/notes'
    | '/_sidebar/shortcuts'
    | '/_sidebar/style'
    | '/notes/$noteId'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SidebarRoute: typeof SidebarRouteWithChildren
  NotesNoteIdRoute: typeof NotesNoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/style': {
      id: '/_sidebar/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof SidebarStyleRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/shortcuts': {
      id: '/_sidebar/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof SidebarShortcutsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/notes': {
      id: '/_sidebar/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof SidebarNotesRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/keyterms': {
      id: '/_sidebar/keyterms'
      path: '/keyterms'
      fullPath: '/keyterms'
      preLoaderRoute: typeof SidebarKeytermsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/home': {
      id: '/_sidebar/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SidebarHomeRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SidebarRouteChildren {
  SidebarHomeRoute: typeof SidebarHomeRoute
  SidebarKeytermsRoute: typeof SidebarKeytermsRoute
  SidebarNotesRoute: typeof SidebarNotesRoute
  SidebarShortcutsRoute: typeof SidebarShortcutsRoute
  SidebarStyleRoute: typeof SidebarStyleRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarHomeRoute: SidebarHomeRoute,
  SidebarKeytermsRoute: SidebarKeytermsRoute,
  SidebarNotesRoute: SidebarNotesRoute,
  SidebarShortcutsRoute: SidebarShortcutsRoute,
  SidebarStyleRoute: SidebarStyleRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SidebarRoute: SidebarRouteWithChildren,
  NotesNoteIdRoute: NotesNoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
